### PR TITLE
[Issue #301] emSensor driver and viewer

### PR DESCRIPTION
**Pull request by lr-morales**
This PR adds driver an viewer for electromagnetic sensors, described in #301.

The documentation strings for the driver aren't finished yet, but at least with this JdeRobot will have a driver in its core.

### CODE REVIEW

**Comment by aitormf** [comment]
I just try this sensor and works pretty well, you can merge it when you want

**Comment by lr-morales** [comment]
I can't merge PRs yet... lack of privileges.

**Comment by fqez** [comment]
Sorry guys! Kinda busy here :P which one should I merge first #534 or #535? Just to be sure!

**Comment by fqez** [comment]
Oh nevermind, I've just read the #536 description. Going up!

**Pull request merged**
