### PR TITLE
Added plugin and model of amazon logistic practice

### PR DESCRIPTION
**Pull request by PabloMorenoVera**
This pull-request fixes the #1162 issue. It's a solution for the amazon_logistic practice.

### CODE REVIEW

**Comment by arsalanakhter** [comment]
Hi Pablo. It'd be nice if you could also share the Gazebo World you had developed for this practice.

**Comment by fqez** [comment]
Hi @PabloMorenoVera and @arsalanakhter is this an alternative for #1161? Or a complement? Should I merge both PR's or only this one?

**Comment by fqez** [comment]
Hi @PabloMorenoVera I am fixing several typos in this PR. Please, test all the code that you want to be merged before sending a pull request, because this particular one doesn't even compile due to names mismatching. I'm fixing this one for you, but take that into account for the future, please.

Good job anyway! Thanks!

**Comment by PabloMorenoVera** [comment]
Hi @arsalanakhter, 
I don't have the world of the amazon practice because it wasn't updated and i use only the robot and a shelving to test the piston.

**Comment by jmplaza** [comment]
Hi @arsalanakhter, it seems that that Gazebo world file was lost on the collapse of @PabloMorenoVera hard disk... It is not available anymore.

**Comment by arsalanakhter** [comment]
Ok.

**Pull request closed without merging**
