### PR TITLE
#1044 & #1015: CameraServer in JS using web technologies and ROS messages and 3D Viewer with NodeJS and Electron

### PR DESCRIPTION
**Pull request by rperezgonz**
cameraserver and 3Dviewer can be launched them in two different ways:

1. As an Electron application
2. From a web browser with nodejs

For Electron, you can follow the installation guide https://electronjs.org/docs/tutorial/installation.

3DViewer still does not connect with 3D Reconstruction of Academy but a test server in python (test_server) is included. Works with ICE Jderobot interface

cameraserver is run with the Roslibjs library and you can launch with the next command (if you have it installed on your pc, otherwise follow the instructions of the following link: http://wiki.ros.org/kinetic/Installation):
`roslaunch rosbridge_server rosbridge_websocket.launch`

This driver is connected with cameraviewjs using socket

### CODE REVIEW

**Comment by fqez** [comment]
Hi @rperezgonz 

impressive PR man! could you provide us a well explained video tutorial showing how to launch and use it? I've seen your mediawiki, but I see no clue about ROScameraviewjs... I'm so lost right now.

Good job!

**Comment by rperezgonz** [comment]
Sorry, It run with the new CameraView-web which I have denveloped. I have already done the pull request with it. The next video show how it run: https://www.youtube.com/watch?v=2BID7Zw1Ntc&feature=youtu.be

**Comment by fqez** [comment]
Hi @rperezgonz I am unable to launch the example as shown in the video you linked, in ubuntu. The server is not able to get images from the camera. Could you provide more information about all the processes involved in this, and how to launch this natively (without docker involved) in ubuntu? It would be useful for us that you make some videos showing:

   * How to connect cameraserver-web with local clients (such as jderobot's cameraview)
   * How to connect cameraserver-web with net tools (such as cameraview-web)

Please, understand that huge commits like this one are difficult to 'follow' and depurate without proper documentation. The video looks really cool, by the way!

Thanks a lot!! :D

**Comment by rperezgonz** [comment]
Hi, at this time camaraserver-web doesn't connect with local clients because the ros message that need to show in a html canvas isn't compatible with jderibots cameraview (it's used sensor_msgs/CompressedImage and not sensor_msgs/Image). I will try to cameraserver-web publish, also, that message type in a future (now I don't know how do it).

To connect it to the cameraview-web, I point you up how do it step by step:

1. Install Rosbridge Server (sudo apt-get install ros-<rosdistro>-rosbridge-server)

2. Launch websocket server (roslaunch rosbridge_server rosbridge_websocket.launch)

3. Put address, port, framerate and rostopic that you want in the yml file and run cameraserver-web with NodeJS or Electron (in the second case, you must install package electron with command **npm install electron** inside of cameraserver-web folder and then run command **npm start**).

4. Run cameraview-web with nodeJS or Electron (in the secon case, you must do the same that you have done with cameraserver). This cameraview is pull request #1081


5. Configure cameraview-web (configuration tab of html) with Ros server and the same information that cameraserver.

The address and port is the same that it use the websocket server (if you want to change it, you will must do in rosbridge_websocket.launch).

In the video, I use robotwebtools docker (https://github.com/RobotWebTools/rwt_dockers/tree/master/demos) to connect the websocket server. this docker does same function as roslaunch rosbridge_server rosbridge_websocket.launch.

In ubuntu, I recorded a video with the first version of cameraserver (https://www.youtube.com/watch?v=H3RvokYPsv4&authuser=0). Only i have changed camera activation (now it is done automatly when it run).

I hope you have clarified your doubts.

**Comment by fqez** [comment]
Hi @rperezgonz thanks for the mini tutorial, it helped a lot! There are some conflicts between this PR (#1073) and the #1081 due to both of them include cameraserver-web within its changes. Can you please delete one of them? The most ancient one, in particular. 

Thanks!

**Comment by aitormf** [comment]
Hi, we have been trying to test this again with no success. We have detected several issues:

1. The configuration file is not loaded porperly due to visibility problems in JS:

````
try{
const yaml = require('js-yaml');
const fs = require('fs');
} catch (e){
  console.log(e);
}
````

There is no visibility of yaml outside that block, so in the next block of code:

````
var config = {};
try {
    config = yaml.safeLoad(fs.readFileSync('public/config.yml', 'utf8'));
} catch (e) {
  console.log(e);
  config.serv = {};
  config.serv.dir = "localhost";
  config.serv.port = "9090";
  config.topic = '/usb_cam/image_raw/compressed';
  config.msgs = "sensor_msgs/CompressedImage";
}
```` 

the code inside the try block is not reached (yaml variable doesn't exists there!)

2- The server cannot access to the camera because you are using a "deprecated" API. See [here:](https://github.com/electron/electron/issues/10174)
Even with that modification we aren't able to reproduce the example porperly, because although the client connects to the camera, the server is not providing any images at all:

````
aitormf@pares:~$ rostopic echo  /usb_cam/image_raw/compressed

header: 
  seq: 3951
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
format: "jpeg"
data: [117, 171, 90]       <-- No image data
```` 
NOTE: Our clients will not work (not web clients) because we do not support compressed images yet (we are working on it), and ROS is serving jpeg images, as shown in the snippet above. But that's our fault.

3- 3DViewer-web is working as a "server". It is asking for data instead of waiting for it, as it does the 3DViewer client (not web one). So you would have to recode the 3DViewer again to make it behave like the not web one.

**Comment by rperezgonz** [comment]
Hi, 
After talk with @jmplaza , to facilitate the tests, I will close the Pull Request and make one for each component, uploading the versions with the problems already solved.
Thanks!

**Pull request closed without merging**
