### PR TITLE
[visualStates] get cmake variables and use in the code and solves #904

### PR DESCRIPTION
**Pull request by okanasik**
This pull request solves following problems
- a new class is created to get install prefix path from cmake variables
- after moving default install prefix to /opt/jderobot some library links are broken in cpp template
- resource locator cannot find glade files since they are not in global glade directory.

### CODE REVIEW

**Comment by lr-morales** [comment]
Good job. 
Not only should solve (I didn't test this to confirm it) the intended issues, but also #485 is partially fixed too.

As I said, I didn't test this PR and maybe I'm wrong, but as CMake is told to generate `cmakevars.hpp` from `cmakevars.hpp.in`, is the inclusion of an already generated file unintended?

Regards

**Comment by okanasik** [comment]
@lr-morales yes I have intentionally included the generated file, but if this is not a good practice, I can remove. What do you think?

**Comment by lr-morales** [comment]
In my opinion, you maybe should remove it as it could mislead someone when looking the code at fist sight and because there have been some issues in the past regarding file generation because some residual generated files were left in the clean source folder: CMake was supposed to generate and take a new file but it used the residual one. 

Did you left it for any special reason? If it was as an example, maybe renaming to something else would also be a good option.

**Comment by okanasik** [comment]
Ok. Then, it will be better if I remove the file. Thanks.

**Comment by aitormf** [comment]
Hi @okanasik , 
with this changes the project doesn't compile:

as configuring the file, it is saved in build, the compiler is unable to find it.
<pre>
/home/kasillas77/git/test/okan2/src/tools/visualStates/generate.cpp:24:25: fatal error: cmakevars.hpp: file or directory doesn't exist
 #include "cmakevars.hpp"
                         ^
compilation terminated.

</pre>
Look at [this](https://github.com/JdeRobot/JdeRobot/blob/master/src/libs/easyiceconfig/CMakeLists.txt) cmakelist to see how to solve it

**Comment by okanasik** [comment]
Thanks for testing. I build in the current directory that is why i did not noticed. It should be fixed with the last commit 7e4032005557ca1156727d17bab56120c4795a07

**Comment by aitormf** [comment]
great job @okanasik !!!

**Pull request merged**
