### PR TITLE
[issue #702 #719] Change in uav_viewer_py

### PR DESCRIPTION
**Pull request by Diegojnb**

### CODE REVIEW

**Comment by aitormf** [comment]
Hi, 
I'm trying the app and all work fine. The only things I've seen that don't fit are  the play button and color filter checkbox. When you delete them from GUI, this PR can be merged

Good job

**Comment by Diegojnb** [comment]
Hi,
I have copied the model that is currently in the official repository under the name of uav_viewer_py and I have changed the way that the speed commands with two joysticks are modified, as would be piloted with a command of any dron.

If it is mandatory to make this change I modify it but currently those buttons appear in the official repository.

**Comment by aitormf** [comment]
This is the actual GUI of Uav Viewer py:
captura de pantalla de 2017-04-04 09-38-30
How you can see, they aren't in the GUI. Delete them please

**Comment by Diegojnb** [comment]
This is actually look like

uav_viewer_py

**Comment by aitormf** [comment]
Merged, 

Thanks @Diegojnb

**Comment by shivangg** [comment]
Please update the ui_gui.ui to current user interface. It still displays this UI when the ui_gui.ui file is opened in Qt Creator

image


rather than the current UI 
image

Only after this update, new features to the GUI of uav_viewer_py can be added like #660

**Comment by jmplaza** [comment]
Solved at #790 @shivangg

**Pull request merged**
