### PR TITLE
Fix #27: Reformat opencvdemo component

### LINKED ISSUE #27: Reformat opencvdemo component
I would like to fix, as an exercise/practice, this:

Syntax and language refactoring:
- [x] Correct syntax as proposed ([Google C++ Style Guide](https://google-styleguide.googlecode.com/svn/trunk/cppguide.html)).
  - [x] Convert real tabs in 2 space characters.
  - [x] Variable names: lower case, only underscore as separator and be descriptive.
  - [x] Class members: add trailing slash.
  - [x] Function names: should start with a capital letter and have a capital letter for each new word without underscores.
- [x] Fixing OpenCV code:
  - [x] Remove `using namespace cv;` (it is a bad practice).
  - [x] Add cv:: prefix to all OpenCV functions/clases.
  - [x] Fix old naming conventions (C styled OpenCV, as `cvLine` -> `cv::line`).
  - [x] Remove all instance destructors managed by OpenCV's automatic memory management.
- [x] Remove unused dependencies in cmake.

Comments and learning value of them:
- [x] Delete old comments holding unused code.
- [x] Add new comments to aid new developers:
  - [x] Descriptive comments.
  - [x] References to OpenCV manual.

New enhancements:
- [x] Fixing glade "IDs".
- [x] Fix convolution code.
- [x] Let glade XML set initial visible state, and not viewer constructor.
- [x] Remove unused code.
- [x] Fix filter order to let Gaussian Blur do it's job before Color Filter, Pyramid before all others, ect.
- [x] Reorder code for readability and/or optimize tasks as show/hide glade blocks.
- [x] Inmunize code against common network errors:
  - [x] Initial connection for proxy creation.
  - [x] Connection issues like timeout (remote server offline) and connection refused (remote server online but remote ice endpoint not running).
- [x] Add support for more image formats:
  - [x] Support for GRAY8 (grey scale).
  - [x] Support for NV21 (AndroidCameraServer).
  - [x] Refactor image conversion to RGB8 using `colorspaces`.
- [x] Add Doxygen support for automatic documentation generation.

Best regards.

### PR DESCRIPTION
**Pull request by ojgarciab**
Details here: https://github.com/RoboticsURJC/JdeRobot/issues/27

A large list of modifications, optimizations, ect.

### CODE REVIEW

**Comment by rocapal** [comment]
Hi @ojgarciab,

Thanks for the contribution!

The JdeRobot dependencies should be in Deps/dependency/CMakeList. You wrote the Doxygen dependency inside of opencvdemo folder. At the moment, the policy about dependencies is that they are checked from the main CMakeLists and enable/disable the components, but never show an error at least the dependency is mandatory for the core libs of JdeRobot

```shell
CMake Error: File /tmp/JdeRobot/src/stable/components/opencvdemo/Doxyfile.in does not exist.
CMake Error at src/stable/components/opencvdemo/CMakeLists.txt:33 (configure_file):
  configure_file Problem configuring file
```

Please change this and pull request again. And please, for the future don't make a pull request with a lot changes. It's very hard for us review 1 pull request with 20 changes than 20 pull requests with 1 change each.

**Comment by ojgarciab** [comment]
Ohh, my fault! I forgot to add Doxyfile.in! thanks for your tip! my local tests worked fine because there was the file, but not in git repository.

And sorry for so many updates, was a large work and I was so excited with the changes that work to refactorize became a bigger and tedious unexpected work.

Now I'm changing the way that the document is generated (always in target "doc") but presence of doxygen tested in Deps, not locally to opencvdemo.

Regards,

**Comment by ojgarciab** [comment]
Please, could you check that all is fine? I have check it twice in my forked repository.

**Comment by ojgarciab** [comment]
I just merge upstream project into my fork to get latest updates (refactor of Image interface). After adding required image format the component works as expected with new cameraserver version.

Remote endpoint changed from 0.0.0.0 back to 127.0.0.1 to avoid confusion between "listen on all address" and ["this host on this network" (see case "a": { 0, 0 })](http://tools.ietf.org/html/rfc1122#page-29), it's best to be explicit about the destination address.

**Comment by ojgarciab** [comment]
Because new fix #45, Deps/doxygen/* files are obsolete and target "doc" is created once. If that pull request is merged before this one then I have to change some files to do not break #45 changes.

I'm working in a new commit to the Fix_27 branch to avoid this dependency problem.

**Comment by ojgarciab** [comment]
Done. Removed Deps/doxygen files and modified CMakeLists.txt to be compatible with new document generation chain.

The documentation block will not be in use (the "if" statement will never be true) until the other pull request will be merged.

**Comment by ojgarciab** [comment]
This pull request is ready to be tested and merged.

**Comment by fqez** [comment]
Tested. Thanks!

**Comment by ojgarciab** [comment]
I'll work in this issue as quick as I can. You are right @fqez , this pull request should have been merged a lot of time ago.

**Comment by varhub** [comment]
Hi @ojgarciab!
If you want to work in this, can I recommend the following?
  * create a branch on top of Fix_27 (Fix_27_resurrect, Fix_27_step2, or whatever)
  * and eventually merge (--no-ff) into Fix_27.

Therefore, anyone can see full changeset at "Files changed" and *conficts resolution* at above generated merge ;) ;)

PS: you can also take current changeset and wrap it in another merge context; just for enhance review task and allow cherry-picking over ancient code.
```
git checkout Fix_27
git reset --hard c68092
git merge --no-ff 92c207e -m "Merge branch 'Fix_27_deprecated' into Fix_27"
git checkout -b Fix_27_resurrect
# begin develop or rebase --commiter-date-is...
```

**Comment by ojgarciab** [comment]
I'm back again, I have time again to review this pull request.

Thanks for the tips @varhub

**Comment by fqez** [comment]
I close this PR because is so ancient. If you want to return on developing this particular issue, let me know and I will reopen it!

Cheers!

**Comment by ojgarciab** [comment]
Thanks.

**Pull request closed without merging**
