### PR TITLE
#729 Disabling ROS when not available

### PR DESCRIPTION
**Pull request by chanfr**

### CODE REVIEW

**Comment by aitormf** [comment]
when I have try to compile Jderobot with this changes, in basic_component, it shows me the following error (in docker without ROS dependencies):

<pre>
[ 45%] Automatic moc for target basic_component
[ 45%] Built target basic_component_automoc
[ 45%] Linking CXX executable basic_component
CMakeFiles/basic_component.dir/basic_component_automoc.cpp.o: In function `GUI::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)':
basic_component_automoc.cpp:(.text+0x0): multiple definition of `GUI::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)'
CMakeFiles/basic_component.dir/gui/moc_gui.cpp.o:moc_gui.cpp:(.text+0x0): first defined here
CMakeFiles/basic_component.dir/basic_component_automoc.cpp.o: In function `GUI::signal_updateGUI()':
basic_component_automoc.cpp:(.text+0x242): multiple definition of `GUI::signal_updateGUI()'
CMakeFiles/basic_component.dir/gui/moc_gui.cpp.o:moc_gui.cpp:(.text+0x242): first defined here
CMakeFiles/basic_component.dir/basic_component_automoc.cpp.o:(.data.rel.ro+0x0): multiple definition of `GUI::staticMetaObject'
CMakeFiles/basic_component.dir/gui/moc_gui.cpp.o:(.data.rel.ro+0x0): first defined here
CMakeFiles/basic_component.dir/basic_component_automoc.cpp.o: In function `GUI::metaObject() const':
basic_component_automoc.cpp:(.text+0x126): multiple definition of `GUI::metaObject() const'
CMakeFiles/basic_component.dir/gui/moc_gui.cpp.o:moc_gui.cpp:(.text+0x126): first defined here
CMakeFiles/basic_component.dir/basic_component_automoc.cpp.o: In function `GUI::qt_metacast(char const*)':
basic_component_automoc.cpp:(.text+0x16e): multiple definition of `GUI::qt_metacast(char const*)'
CMakeFiles/basic_component.dir/gui/moc_gui.cpp.o:moc_gui.cpp:(.text+0x16e): first defined here
CMakeFiles/basic_component.dir/basic_component_automoc.cpp.o: In function `GUI::qt_metacall(QMetaObject::Call, int, void**)':
basic_component_automoc.cpp:(.text+0x1be): multiple definition of `GUI::qt_metacall(QMetaObject::Call, int, void**)'
CMakeFiles/basic_component.dir/gui/moc_gui.cpp.o:moc_gui.cpp:(.text+0x1be): first defined here
CMakeFiles/basic_component.dir/basic_component_automoc.cpp.o: In function `CamerasWidget::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)':
basic_component_automoc.cpp:(.text+0x26e): multiple definition of `CamerasWidget::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)'
CMakeFiles/basic_component.dir/gui/widget/moc_cameraswidget.cpp.o:moc_cameraswidget.cpp:(.text+0x0): first defined here
CMakeFiles/basic_component.dir/basic_component_automoc.cpp.o:(.data.rel.ro+0x40): multiple definition of `CamerasWidget::staticMetaObject'
CMakeFiles/basic_component.dir/gui/widget/moc_cameraswidget.cpp.o:(.data.rel.ro+0x0): first defined here
CMakeFiles/basic_component.dir/basic_component_automoc.cpp.o: In function `CamerasWidget::metaObject() const':
basic_component_automoc.cpp:(.text+0x284): multiple definition of `CamerasWidget::metaObject() const'
CMakeFiles/basic_component.dir/gui/widget/moc_cameraswidget.cpp.o:moc_cameraswidget.cpp:(.text+0x16): first defined here
CMakeFiles/basic_component.dir/basic_component_automoc.cpp.o: In function `CamerasWidget::qt_metacast(char const*)':
basic_component_automoc.cpp:(.text+0x2cc): multiple definition of `CamerasWidget::qt_metacast(char const*)'
CMakeFiles/basic_component.dir/gui/widget/moc_cameraswidget.cpp.o:moc_cameraswidget.cpp:(.text+0x5e): first defined here
CMakeFiles/basic_component.dir/basic_component_automoc.cpp.o: In function `CamerasWidget::qt_metacall(QMetaObject::Call, int, void**)':
basic_component_automoc.cpp:(.text+0x31c): multiple definition of `CamerasWidget::qt_metacall(QMetaObject::Call, int, void**)'
CMakeFiles/basic_component.dir/gui/widget/moc_cameraswidget.cpp.o:moc_cameraswidget.cpp:(.text+0xae): first defined here
CMakeFiles/basic_component.dir/basic_component_automoc.cpp.o: In function `controlVW::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)':
basic_component_automoc.cpp:(.text+0x35c): multiple definition of `controlVW::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)'
CMakeFiles/basic_component.dir/gui/widget/moc_controlvw.cpp.o:moc_controlvw.cpp:(.text+0x0): first defined here
CMakeFiles/basic_component.dir/basic_component_automoc.cpp.o: In function `controlVW::VW_changed(float, float)':
basic_component_automoc.cpp:(.text+0x534): multiple definition of `controlVW::VW_changed(float, float)'
CMakeFiles/basic_component.dir/gui/widget/moc_controlvw.cpp.o:moc_controlvw.cpp:(.text+0x1d8): first defined here
CMakeFiles/basic_component.dir/basic_component_automoc.cpp.o:(.data.rel.ro+0x80): multiple definition of `controlVW::staticMetaObject'
CMakeFiles/basic_component.dir/gui/widget/moc_controlvw.cpp.o:(.data.rel.ro+0x0): first defined here
CMakeFiles/basic_component.dir/basic_component_automoc.cpp.o: In function `controlVW::metaObject() const':
basic_component_automoc.cpp:(.text+0x418): multiple definition of `controlVW::metaObject() const'
CMakeFiles/basic_component.dir/gui/widget/moc_controlvw.cpp.o:moc_controlvw.cpp:(.text+0xbc): first defined here
CMakeFiles/basic_component.dir/basic_component_automoc.cpp.o: In function `controlVW::qt_metacast(char const*)':
basic_component_automoc.cpp:(.text+0x460): multiple definition of `controlVW::qt_metacast(char const*)'
CMakeFiles/basic_component.dir/gui/widget/moc_controlvw.cpp.o:moc_controlvw.cpp:(.text+0x104): first defined here
CMakeFiles/basic_component.dir/basic_component_automoc.cpp.o: In function `controlVW::qt_metacall(QMetaObject::Call, int, void**)':
basic_component_automoc.cpp:(.text+0x4b0): multiple definition of `controlVW::qt_metacall(QMetaObject::Call, int, void**)'
CMakeFiles/basic_component.dir/gui/widget/moc_controlvw.cpp.o:moc_controlvw.cpp:(.text+0x154): first defined here
collect2: error: ld returned 1 exit status
src/tools/basic_component/CMakeFiles/basic_component.dir/build.make:432: recipe for target 'src/tools/basic_component/basic_component' failed
make[2]: *** [src/tools/basic_component/basic_component] Error 1
CMakeFiles/Makefile2:2492: recipe for target 'src/tools/basic_component/CMakeFiles/basic_component.dir/all' failed
make[1]: *** [src/tools/basic_component/CMakeFiles/basic_component.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
</pre>

**Comment by chanfr** [comment]
Try now.

**Comment by aitormf** [comment]
all work well.

only you need delete **${easyiceconfig_LIBRARY_DIRS}** line ( 57 ) of basic_component CMakeLists because it shows the following warning in cmake:

<pre>
WARNING: Target "basic_component" requests linking to directory "/root/JdeRobot/build/src/libs/easyiceconfig".  Targets may link only to libraries.  CMake is dropping the item.
</pre>
when it is deleted, this PR can be merged

**Comment by chanfr** [comment]
Ups.... fixed!

**Pull request merged**
