### PR TITLE
[Issue #485] Replaces install prefix in CMakeLists.txt and adds python dependency

### PR DESCRIPTION
**Pull request by lr-morales**
This PR should fix the issue #485 **only** for the main CMakeLists.txt.

Also a Deps for python2 is included, as at this moment the project is assuming that a python 2.x interpreter exists in the system, that has the default directory tree and that the python version is exactly 2.7; now CMake should check for that.

### CODE REVIEW

**Comment by aitormf** [comment]
This PR adds stable level in root CMakeLists and the installation is not well, but gives no error.

for example in Install section, it changes: 
`INSTALL(FILES ${CMAKE_CURRENT_BINARY_DIR}/src/interfaces/libJderobotInterfaces.so DESTINATION /usr/local/lib/jderobot COMPONENT core)`

by:
`INSTALL(FILES ${CMAKE_CURRENT_BINARY_DIR}/src/stable/interfaces/libJderobotInterfaces.so DESTINATION ${CMAKE_INSTALL_PREFIX}/lib/jderobot COMPONENT core) `

**Comment by lr-morales** [comment]
I'll fix it ASAP. Sorry for the bug.

**Comment by lr-morales** [comment]
All old "stable" directory references should be fixed now, @aitormf.

**Comment by aitormf** [comment]
All works well, I don't see any problem now

**Pull request merged**
