### PR TITLE
Issue #690: Added Monaco F1 track world and model.

### PR DESCRIPTION
**Pull request by kb8alvaro**
Issue #690 solved, created and added the world with the F1 track of Montecarlo.
Uploaded monaco.world and monaco folder with the model of the track, should be structured as the ones already made.

If there is something wrong tell me to fix it.

### CODE REVIEW

**Comment by fqez** [comment]
Hi @kb8alvaro 

very nice job! We have seen a couple of problems:

* The first one is the scale of the circuit, it's too small even for the F1 car. The attached image shows the issue. The only thing you have to edit is the scale factor in the model.sdf file. Inside the <mesh> tag, you should include an <scale> tag with the scale for X, Y and Z axis. We have tested <scale>40 40 40</scale> and seems pretty good for the F1.

* The other issue is related with the colission with the ground. If you launch the model in gazebo with no ground in it, the model falls indefinitely, so you have to add a ground for the circuit. You can see how the simpleCircuit model is done to fix this.

the rest of the PR seems good :D Nicely done!

algo

**Comment by kb8alvaro** [comment]
Thanks for testing! I'll scale it properly and have it in mind for the next tracks.

Just one question, Shouldn't it have the collision with the model instead of adding something extra? I'm working on doing the same track with elevations and high grounds as the real track, and I won't be able to fix the collisions that way. How could I add the collisions to the model so the cars can go up and downhill?

Thanks!

**Comment by kb8alvaro** [comment]
A lot of progress made in this commit:

- 4 versions of the track: flat, flat with red line, elevations, and elevations with red line. Each one with it's *.world

- Scaled all tracks to a bit less than three f1 cars wide

- Cutted off corners and tweaked textures to lighten the size and the visual rendering in gazebo, should be much smooth now

- Now collision works, just needed to add collisions and physics in Blender. If the cars bounce weird or the grip is not as it should  tell me, because I need to change the parameters in Blender and reload the model.

Hope everything works fine!

**Comment by aitormf** [comment]
Hi @kb8alvaro , 
 I have tried the four worlds that you add:

- **monaco.world**, **monacoLine.world** and **monacoelevations.world**  fall, they haven't floor.
- **monacoElevations.world** shows me the following error:
<pre>
Error [parser.cc:689] Unable to find uri[model://monacoelevations]
</pre>

**Comment by kb8alvaro** [comment]
Solved! Sorry, it was a stupid line of code that was marking the track as non-static, and a mistake with capitals when naming the files. it should work fine now

**Comment by aitormf** [comment]
Hi @kb8alvaro, 

I'm back to try the worlds with your modifications and all less **monacoElevations.world** works fine.

**monacoElevations.world** only has a bigger cube:

captura de pantalla de 2017-04-13 11-56-19

**Comment by kb8alvaro** [comment]
Yeah, that was a problem with the path of the model. I found also a problem with the textures. I tested it on my PC and should work fine now.

**Comment by aitormf** [comment]
all OK,

thanks @kb8alvaro !!!!

**Pull request merged**
