### PR TITLE
[Issue #792] Fix compilation warnings - some warnings addressed

### PR DESCRIPTION
**Pull request by lr-morales**
This PR should address some of the compilation warnings produced when building JdeRobot, mostly non-return (as best as could without changing function return type) and unsigned comparison warnings.

### CODE REVIEW

**Comment by aitormf** [comment]
all works for me

**Comment by fqez** [comment]
Nice job

@lr-morales are you planning on keep adressing warnings? Or should we merge this already?

Cheers!

**Comment by lr-morales** [comment]
I have located some more "easy-to-solve" warnings, we can wait them before merging. I can comment again when I finish or feel that solving more warnings would take long in order to merge the ones already solved an checked.

**Comment by lr-morales** [comment]
Hello,

this PR should be ready about the "easy-to-solve" warnings, the remaining warnings should be the ones  pointed at the issue #792. 
@fqez, @aitormf: I think these should be reviewed and merge first and then start addressing the remaining ones.

**Comment by aitormf** [comment]
It's all Ok for me, good job @lr-morales

**Pull request merged**
